name: rawg
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.9
  states_rebuilder: ^2.1.0
  google_fonts: ^1.1.0
  cached_network_image: ^2.2.0+1
  url_launcher: ^5.4.10
  intl: ^0.16.1
  flutter_svg: ^0.17.4
  logger: ^0.9.1
  semaphore: ^0.1.4
  mime_type: ^0.3.1
  flutter_widgets: ^0.1.12
  uuid: ^2.1.0
  flutter_image_compress: ^0.6.8
  flutter_cache_manager: ^1.4.1
  enum_to_string: ^1.0.9

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - Assets/platformicons/andriod.svg
     - Assets/platformicons/apple.svg
     - Assets/platformicons/linux.svg
     - Assets/platformicons/nitendo.svg
     - Assets/platformicons/ps4.svg
     - Assets/platformicons/windows.svg
     - Assets/platformicons/xbox.svg
     - Assets/storeicons/xbox360store.svg
     - Assets/storeicons/steam.svg
     - Assets/storeicons/gog.svg
     - Assets/storeicons/ps.svg
     - Assets/storeicons/nitendo.svg
     - Assets/storeicons/epicgames.svg
     - Assets/storeicons/appstore.svg
     - Assets/storeicons/googleplaystore.svg
     -
     - Assets/genresicons/Action.png
     - Assets/genresicons/Adventure.png
     - Assets/genresicons/Puzzle.png
     - Assets/genresicons/Racing.png
     - Assets/genresicons/Rpg.png
     - Assets/genresicons/Shooter.png
     - Assets/genresicons/Sports.png
     - Assets/genresicons/Strategy.png

