name: gameg
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.9
  states_rebuilder: ^2.1.0
  google_fonts: ^1.1.0
  url_launcher: ^5.4.10
  intl: ^0.16.1
  flutter_svg: ^0.17.4
  logger: ^0.9.1
  semaphore: ^0.1.4
  mime_type: ^0.3.1
  flutter_widgets: ^0.1.12
  uuid: ^2.1.0
  flutter_image_compress: ^0.6.8
  flutter_cache_manager: ^1.4.1
  enum_to_string: ^1.0.9
  flutter_launcher_icons: ^0.7.5
  cupertino_icons: ^0.1.3
  flutter_native_splash: ^0.1.9



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "gameg_launcher_icon"
  ios: false
  image_path: "Assets/gameglogo.png"

flutter_native_splash:
  image: Assets/gameglogo.png
  color: "191D20"
  android_disable_fullscreen: true
  
flutter:
  uses-material-design: true
  assets:
     - Assets/platformicons/Andriod_Icon.svg
     - Assets/platformicons/Apple_Icon.svg
     - Assets/platformicons/Linux_Icon.svg
     - Assets/platformicons/Nitendo_Icon.svg
     - Assets/platformicons/PS4_Icon.svg
     - Assets/platformicons/Windows_Icon.svg
     - Assets/platformicons/Xbox_Icon.svg

     - Assets/interfaceicons/Back_Icon.svg
     - Assets/interfaceicons/Dislike_Icon.svg
     - Assets/interfaceicons/Fav_Icon.svg
     - Assets/interfaceicons/Filter_Icon.svg
     - Assets/interfaceicons/Like_Icon.svg
     - Assets/interfaceicons/Like_Icon.svg
     - Assets/interfaceicons/Search_Icon.svg
     - Assets/interfaceicons/Tick_Icon.svg

     - Assets/storeicons/xbox360store.svg
     - Assets/storeicons/steam.svg
     - Assets/storeicons/gog.svg
     - Assets/storeicons/ps.svg
     - Assets/storeicons/nitendo.svg
     - Assets/storeicons/epicgames.svg
     - Assets/storeicons/appstore.svg
     - Assets/storeicons/googleplaystore.svg

     - Assets/genresicons/Action.png
     - Assets/genresicons/Adventure.png
     - Assets/genresicons/Puzzle.png
     - Assets/genresicons/Racing.png
     - Assets/genresicons/Rpg.png
     - Assets/genresicons/Shooter.png
     - Assets/genresicons/Sports.png
     - Assets/genresicons/Strategy.png

     - Assets/erroricons/Robo_Icon.svg
